### ISSUE TITLE
Essence forecast issue impacting recommendations based on 'time_to_max'

### ISSUE THREAD

**Issue by W8ink** [Hekili/hekili#1980]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Issue in essence tracking when essence >= 4 . same with essence.time_to_max it stuck on 4 sec.

### How to Reproduce

1. Enter game as Dev Evoker.
2. Spend essence.
3. Watch state of essence.time_to_max
![1](https://user-images.githubusercontent.com/105168976/202536762-96b2c1e8-d0ba-4261-885a-6d898ff2e3d7.jpg)

### Talent Loadout

BsbBAAAAAAAAAAAAAAAAAAAAAAIAAAAAAgWIJikQgEJlkkASLgESSAJJSESSC

### Snapshot

https://pastebin.com/tUGMVFee

### Contact Information

W8ink#7189

**Comment by W8ink** [comment]
first time creating report wrong category...

**Comment by Hekili** [comment]
Thanks for the report.  I am testing a solution for this now; fundamentally, the problem is that the base UI does not give information about progress as Essence regenerates.  I mostly have it solved now and will post in the next release.

**Comment by W8ink** [comment]
excellent!

**Comment by Hekili** [comment]
This should be addressed in the latest release (10.0.2-1.5).  Let me know if you are still seeing issues.

**Comment by W8ink** [comment]
> This should be addressed in the latest release (10.0.2-1.5). Let me know if you are still seeing issues.

the issue remains. its hard to explain what exactly happens.
lets begin from where issue appears.
![image](https://user-images.githubusercontent.com/105168976/202865958-7f0f55bc-d58d-444f-a8fa-6024f4511065.png)
when i have 0 essence its ok with essence.current but essence.time_to_max doesn't work properly.
![image](https://user-images.githubusercontent.com/105168976/202866042-a0871eb3-5135-4c19-9ff3-450254e68fb5.png)
when i have 3 essence all conditions work as it must work
![image](https://user-images.githubusercontent.com/105168976/202866156-100328d2-bbb3-4bda-a032-76036e1f3b63.png)
when i just get 5 all contitions show wrong values.

10.0.2-1.5 fix did not solve the problem completely.
That's all I have at the moment.
since English is not my native language somewhere I could not correctly express my thought.

**Comment by Hekili** [comment]
@W8ink Thanks for more information.

1st screenshot is actually fine.  When it'll take longer than the allowable window for the addon to make a decision, resource forecasting just assumes things aren't going to happen.  That's where 3600 comes from.  Going from 0 to 5 is simply longer than the threshold the addon needs to care about.

2nd screenshot differs because the time it takes to go from 3 to 5 is within the period of time the addon cares about.

3rd screenshot is interesting.  You can't trust the UI at some times.  First, I'm going to assume you changed talents so that you actually do have a maximum of 6 Essence, since that's a change from the prior two screenshots and you didn't mention doing that.  However, the animations in the default UI for Essence regeneration are also misleading.

Example:
![Essence](https://user-images.githubusercontent.com/9438134/202874371-4eddecca-0aa3-4dea-827c-165db3c2324f.gif)

In this GIF, I spent two Essence, then I allowed Essence to partially regenerate so that the 5th Essence is about halfway full and spent Essence again.  Essence drops to 2 -- the half regen doesn't show in the UI -- but when third Essence halfway regenerates, it suddenly snaps to full.

So tell me the impact here.  What impact to recommendations are you seeing since 1.5 released that appear incorrect?  In order to calculate Essence regeneration, I have to track the time that Essence starts regenerating in a way the UI itself doesn't provide.  Let me know (with snapshots) if/when you see actual recommendations that appear wrong.  Unfortunately, we can't rely on the default UI elements to be accurate about Essence regen.

**Comment by Hekili** [comment]
In the wake of another ticket, I'm making modifications to the options UI so that those preview tooltips will have more accurate information.  In some situations, the game state wasn't being reset before generating the preview.  This could impact current Essence and time_to_max as well.

**Comment by Hekili** [comment]
This should be resolved in 1.6.1 which is being built now.
