### ISSUE TITLE
After updating addons Hekili ui disappeared

### ISSUE THREAD

**Issue by Pyxl00** [Hekili/hekili#2232]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

After updating all of my addons, the Hekili UI, other than the bubble next to the minimap disappeared off of my screen.

### How to Reproduce

Switched from Devastation Evoker to a Preservation Evoker and same problem occured.

### Player Information (Link)

```Text
build: v10.0.2-2.0.10
level: 70 (70)
class: EVOKER
spec: devastation

talents: aerial_mastery
    animosity = 1/1
    arcane_intensity = 2/2
    azure_essence_burst = 1/1
    blast_furnace = 2/2
    burnout = 2/2
    catalyze = 1/1
    causality = 1/1
    cauterizing_flame = 1/1
    charged_blast = 1/1
    dense_energy = 1/1
    dragonrage = 1/1
    engulfing_blaze = 1/1
    enkindled = 2/2
    essence_attunement = 1/1
    eternity_surge = 1/1
    eternitys_span = 1/1
    expunge = 1/1
    extended_flight = 2/2
    feed_the_flames = 1/1
    fire_within = 1/1
    font_of_magic = 1/1
    heat_wave = 2/2
    inherent_resistance = 2/2
    inner_radiance = 1/1
    instinctive_arcana = 2/2
    landslide = 1/1
    leaping_flames = 1/1
    natural_convergence = 1/1
    obsidian_bulwark = 1/1
    obsidian_scales = 1/1
    onyx_legacy = 1/1
    panacea = 1/1
    permeating_chill = 1/1
    protracted_talons = 1/1
    pyre = 1/1
    quell = 1/1
    regenerative_magic = 1/1
    renewing_blaze = 1/1
    rescue = 1/1
    ruby_essence_burst = 1/1
    scarlet_adaptation = 1/1
    scintillation = 2/2
    shattering_star = 1/1
    source_of_magic = 1/1
    spellweavers_dominance = 1/1
    tailwind = 1/1
    terror_of_the_skies = 1/1
    tip_the_scales = 1/1
    tyranny = 1/1
    verdant_embrace = 1/1
    volatility = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: [plague_deviser_marileth]

sets: primal_ritual_shell = 1
    ruby_whelp_shell = 1
    tier29 = 2

gear: basalt_brood_stompers = 1
    blaze_ring = 1
    blazebound_lieutenants_helm = 1
    crimson_gladiators_chain_tunic = 1
    drakebreakers_staff = 1
    emboldened_dracthyrs_tabard = 1
    gauntlets_of_the_awakened = 1
    obsidian_cape = 1
    obsidian_collar = 1
    ohnahran_falconers_belt = 1
    ohnahran_falconers_greaves = 1
    primal_ritual_shell = 1
    ring_of_embers = 1
    ruby_whelp_shell = 1
    surgingsong_conductors = 1
    talons_of_the_awakened = 1
    tier29 = 2

legendaries: none

itemIDs: 192001, 192037, 193757, 193765, 195516, 199081, 200159, 200163, 200380, 200383, 200563, 200661, 200970, 200971, 201505, 202197

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxTime = 10
    nameplateRange = 35
    nameplates = false
    noFeignedCooldown = false
    package = Devastation
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    use_clipping = false
    use_deep_breath = true
    use_early_chain = false
    use_unravel = true

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = false [overridden]
    interrupts = false 
    mode = dual 
    potions = false 

keybinds: 
    action_return          = T   [05]
    azure_strike           = 2   [01]
    blessing_of_the_bronze = F11 [06]
    cauterizing_flame      = I   [05]
    deep_breath            = =   [01]
    disintegrate           = 5   [01]
    dragonrage             = 0   [01]
    emerald_blossom        = F3  [06]
    eternity_surge         = 9   [01]
    expunge                = F4  [06]
    fire_breath            = 6   [01]
    fury_of_the_aspects    = F12 [06]
    healthstone            = U   [05]
    hover                  = F2  [06]
    landslide              = -   [01]
    living_flame           = 1   [01]
    obsidian_scales        = F9  [06]
    pyre                   = 7   [01], 1   [02]
    quell                  = F1  [06]
    renewing_blaze         = F7  [06]
    rescue                 = Y   [05]
    shattering_star        = 8   [01]
    source_of_magic        = F10 [06]
    tail_swipe             = 4   [01]
    tip_the_scales         = F8  [06]
    unravel                = F6  [06]
    verdant_embrace        = F5  [06]
    wing_buffet            = 3   [01]

warnings: [#1] Update: Interface/AddOns/Hekili/State.lua:3538: C stack overflow
[string "@Interface/AddOns/Hekili/State.lua"]:3538: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
...
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:2187: in function <Interface/AddOns/Hekili/State.lua:1883>
[string "@Interface/AddOns/Hekili/State.lua"]:3567: in function <Interface/AddOns/Hekili/State.lua:3534>
[string "@Interface/AddOns/Hekili/State.lua"]:7137: in function `TimeToReady'
[string "@Interface/AddOns/Hekili/Core.lua"]:830: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1416: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1811: in function <Interface/AddOns/Hekili/Core.lua:1478>
```

### Error Messages (Link)

```Text
You have no bugs, yay!
```

**Comment by Hekili** [comment]
There was an open ticket for Evoker already; this has been resolved in 2.0.11.

**Comment by Pyxl00** [comment]
Would you be able to link the post? I didnt see it there. This also started this morning when I logged on. It was working last night

**Comment by Pyxl00** [comment]
I also disabled all my other addons and tried only Hekili by itself and it still didnt show on my UI.

**Comment by Hekili** [comment]
Update to 2.0.11.

**Comment by Pyxl00** [comment]
Still not showing up after updating to 2.0.11. Got a bug report also from pausing the addon. 

3x Hekili/State.lua:2185: C stack overflow
[string "@Hekili/State.lua"]:2185: in function <Hekili/State.lua:1883>
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
[string "@Hekili/State.lua"]:2187: in function <Hekili/State.lua:1883>
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
[string "@Hekili/State.lua"]:2187: in function <Hekili/State.lua:1883>
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
[string "@Hekili/State.lua"]:2187: in function <Hekili/State.lua:1883>
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
[string "@Hekili/State.lua"]:2187: in function <Hekili/State.lua:1883>
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
[string "@Hekili/State.lua"]:2187: in function <Hekili/State.lua:1883>
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
...
[string "@Hekili/State.lua"]:3567: in function <Hekili/State.lua:3534>
[string "@Hekili/State.lua"]:7137: in function `TimeToReady'
[string "@Hekili/Core.lua"]:830: in function `GetPredictionFromAPL'
[string "@Hekili/Core.lua"]:1416: in function `GetNextPrediction'
[string "@Hekili/Core.lua"]:1811: in function `Update'
[string "@Hekili/Options.lua"]:10669: in function `MakeSnapshot'
[string "@Hekili/Options.lua"]:10626: in function <Hekili/Options.lua:10621>
[string "=(tail call)"]: ?
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals:
t = <table> {
 swing = <table> {
 }
 FindPlayerAuraByID = <function> defined @Hekili/Utils.lua:516
 summonPet = <function> defined @Hekili/State.lua:1112
 role = <table> {
 }
 IsKnown = <function> defined @Hekili/State.lua:6718
 UnitGUID = <function> defined =[C]:-1
 purge = <table> {
 }
 stat = <table> {
 }
 ptr = 0
 off_hand = <table> {
 }
 floor = <function> defined =[C]:-1
 essence = <table> {
 }
 tonumber = <function> defined =[C]:-1
 predictionsOff = <table> {
 }
 holds = <table> {
 }
 display = "Primary"
 prev_off_gcd = <table> {
 }
 SetDefaultVariable = <function> defined @Hekili/State.lua:4277
 mainhand_speed = 3.203000
 channelSpell = <function> defined @Hekili/State.lua:1175
 equipped = <table> {
 }
 gain = <function> defined @Hekili/State.lua:1478
 TimeToReady = <function> defined @Hekili/State.lua:7073
 setStance = <function> defined @Hekili/State.lua:1086
 history = <table> {
 }
 varPaths = <table> {
 }
 args = <table> {
 }
 UnitAura = <function> defined =[C]:-1
 AddToHistory = <function> defined @Hekili/Events.lua:989
 SetupCycle = <function> defined @Hekili/State.lua:755
 print = <function> defined @Hekili/State.lua:530
 GetSpellCount = <function> defined =[C]:-1
 ClashOffset = <function> defined @Hekili/State.lua:7287
 azerite = <table> {
 }
 offset = 0
 QueuedCastRemains = <function> defined @Hekili/State.lua:6006
 ApplyCastingAuraFromQueue = <function> defined @Hekili/State.lua:6030
 TargetBuffUp = <function> defined @Hekili/State.lua:5562
 pvptalent = <table> {
 }
 delayMin = 0
 GetItemGem = <function> defined =[C]:-1
 UnitIsFriend = <function> defined =[C]:-1
 action = <table> {
 }
 addStack = <function> defined @Hekili/State.lua:960
 HasRequiredResources = <function> defined @Hekili/State.lua:7036
 TargetDebuffUp = <function> defined @Hekili/State.lua:5567
 UnitCanAttack = <function> defined =[C]:-1
 rawSpend = <function> defined @Hekili/State.lua:1498
 script = <table> {
 }
 IsUsable = <function> defined @Hekili/State.lua:6894
 GetItemInfo = <function> defined =[C]:-1
 GetPlayerAuraBySpellID = <function> defined =[C]:-1
 health = <table> {
 }
 IsFiltered = <function> defined @Hekili/State.lua:6861
 cooldown = <table> {
 }
 stance = <table> {
 }
 gcd = <table> {
 }
 empowerment = <table> {
 }
 varDB = <table> {
 }
 ResetQueues = <function> defined @Hekili/State.lua:5815
 auras = <table> {
 }
 GetCycleInfo = <function> defined @Hekili/State.lua:807
 format = <function> defined =[C]:-1
 using_apl = <table> {
 }
 RemoveAuraEvent = <function> defined @Hekili/State.lua:5688
 system = <table> {
 }
 recheckTimes = <table> {
 }
 runHandler = <function> defined @Hekili/State.lua:6113
 recheck = <function> defined @Hekili/State.lua:1541
 GetShapeshiftFormInfo = <function> defined =[C]:-1
 nextOH = 0
 main_hand = <table> {
 }
 IsActiveSpell = <function> defined @Hekili/Utils.lua:573
 GetEventInfo = <function> defined @Hekili/State.lua:5733
 artifact = <table> {
 }
 ceil = <function> defined =[C]:-1
 talent = <table> {
 }
 GetSpellInfo = <function> defined =[C]:-1
 covenant = <table> {
 }
 FindRaidBuffByID = <function> defined @Hekili/Utils.lua:293
 InFlightRemains = <function> defined @Hekili/State.lua:5976
 IsDisabled = <function> defined @Hekili/State.lua:6816
 IsSpellKnownOrOverridesKnown = <function> defined =[C]:-1
 predictionsOn = <table> {
 }
 aura = <table> {
 }
 IsReady = <function> defined @Hekili/State.lua:7203
 IsCycling = <function> defined @Hekili/State.lua:824
 IsChanneling = <function> defined @Hekili/State.lua:6019
 AddResour

**Comment by Hekili** [comment]
If you type `/hekili` and go to the Issue Reporting tab, what does the first line say in Character Data?

**Comment by Pyxl00** [comment]
build: v10.0.2-2.0.11
level: 70 (70)
class: EVOKER
spec: devastation

talents: aerial_mastery
    animosity = 1/1
    arcane_intensity = 2/2
    azure_essence_burst = 1/1
    blast_furnace = 2/2
    burnout = 2/2
    catalyze = 1/1
    causality = 1/1
    cauterizing_flame = 1/1
    charged_blast = 1/1
    dense_energy = 1/1
    dragonrage = 1/1
    engulfing_blaze = 1/1
    enkindled = 2/2
    essence_attunement = 1/1
    eternity_surge = 1/1
    eternitys_span = 1/1
    expunge = 1/1
    extended_flight = 2/2
    feed_the_flames = 1/1
    fire_within = 1/1
    font_of_magic = 1/1
    heat_wave = 2/2
    inherent_resistance = 2/2
    inner_radiance = 1/1
    instinctive_arcana = 2/2
    landslide = 1/1
    leaping_flames = 1/1
    natural_convergence = 1/1
    obsidian_bulwark = 1/1
    obsidian_scales = 1/1
    onyx_legacy = 1/1
    panacea = 1/1
    permeating_chill = 1/1
    protracted_talons = 1/1
    pyre = 1/1
    quell = 1/1
    regenerative_magic = 1/1
    renewing_blaze = 1/1
    rescue = 1/1
    ruby_essence_burst = 1/1
    scarlet_adaptation = 1/1
    scintillation = 2/2
    shattering_star = 1/1
    source_of_magic = 1/1
    spellweavers_dominance = 1/1
    tailwind = 1/1
    terror_of_the_skies = 1/1
    tip_the_scales = 1/1
    tyranny = 1/1
    verdant_embrace = 1/1
    volatility = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: [plague_deviser_marileth]

sets: primal_ritual_shell = 1
    ruby_whelp_shell = 1
    tier29 = 2

gear: basalt_brood_stompers = 1
    blaze_ring = 1
    blazebound_lieutenants_helm = 1
    crimson_gladiators_chain_tunic = 1
    drakebreakers_staff = 1
    emboldened_dracthyrs_tabard = 1
    gauntlets_of_the_awakened = 1
    obsidian_cape = 1
    obsidian_collar = 1
    ohnahran_falconers_belt = 1
    ohnahran_falconers_greaves = 1
    primal_ritual_shell = 1
    ring_of_embers = 1
    ruby_whelp_shell = 1
    surgingsong_conductors = 1
    talons_of_the_awakened = 1
    tier29 = 2

legendaries: none

itemIDs: 192001, 192037, 193757, 193765, 195516, 199081, 200159, 200163, 200380, 200383, 200563, 200661, 200970, 200971, 201505, 202197

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = false
    maxTime = 10
    nameplateRange = 35
    nameplates = false
    noFeignedCooldown = false
    package = Devastation
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    use_clipping = false
    use_deep_breath = true
    use_early_chain = false
    use_unravel = true

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    action_return          = T   [05]
    azure_strike           = 2   [01]
    blessing_of_the_bronze = F11 [06]
    cauterizing_flame      = I   [05]
    deep_breath            = =   [01]
    disintegrate           = 5   [01]
    dragonrage             = 0   [01]
    emerald_blossom        = F3  [06]
    eternity_surge         = 9   [01]
    expunge                = F4  [06]
    fire_breath            = 6   [01]
    fury_of_the_aspects    = F12 [06]
    healthstone            = U   [05]
    hover                  = F2  [06]
    landslide              = -   [01]
    living_flame           = 1   [01]
    obsidian_scales        = F9  [06]
    pyre                   = 7   [01], 1   [02]
    quell                  = F1  [06]
    renewing_blaze         = F7  [06]
    rescue                 = Y   [05]
    shattering_star        = 8   [01]
    source_of_magic        = F10 [06]
    tail_swipe             = 4   [01]
    tip_the_scales         = F8  [06]
    unravel                = F6  [06]
    verdant_embrace        = F5  [06]
    wing_buffet            = 3   [01]

warnings: none

**Comment by Hekili** [comment]
Can you provide the following details?

1. Your talent export string.
2. The output from typing `/dump Hekili.Class.auras.blessing_of_the_bronze` in chat.
3. Confirm if the issue appears if you cast Blessing of the Bronze (or, if you have the buff up, if you remove it).

**Comment by Pyxl00** [comment]
Its super odd. The addon randomly started working. F11'd back to the game and everything was just there. Ill provided the details though just incase its not a temporary issue

1. BsbBnWR3R1Z1HmbUKIpvm3XXhDAAAAAAAKahkISSkQSk0SSSLi0QiESiESSSSEkkA

**Comment by Pyxl00** [comment]
You may be right that it may have been Blessing of the Bronze that ended its duration.
