### ISSUE TITLE
[REC] WW Monk - Tiger Palm during Serenity

### ISSUE THREAD

**Issue by Zifrost** [Hekili/hekili#3112]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Serenity window for WW should be corrected as it call to use Tiger Palm to regen Chi but Serenity dont consume Chi, and using TP in that window is a big dps loss. U should use Tiger palm before going in Serenity to not waste Chi Generator.
as u only want to use Chi spender

### How to Reproduce

Pick Serenity talent as WW monk, start the fight

### Snapshot (Link)

https://pastebin.com/8wgDVtfa

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/gtJGHG8tAWBwoAmUK3kqim

### Contact Information

Discord ID: zifrost

**Comment by Hekili** [comment]
Thanks, this should be resolved today or tomorrow.

**Comment by Zifrost** [comment]
Hi,
Have u deployed the update?

________________________________
Da: Hekili ***@***.***>
Inviato: martedì 9 gennaio 2024 15:46
A: Hekili/hekili ***@***.***>
Cc: Zifrost ***@***.***>; Author ***@***.***>
Oggetto: Re: [Hekili/hekili] WW Monk in Serenity winsow, wrong priorities (Issue #3112)


Thanks, this should be resolved today or tomorrow.

**Comment by antoine100** [comment]
WW is still using Tiger palm during serenity as on 10.2.0-1.1.2a

**Comment by Zifrost** [comment]
This is not a my review of log, Just picked one random but they clearly
suggest to not use Tiger Palm in Serenity.
You have to use it before then go in Serenity.

Il giorno gio 11 gen 2024 alle 04:51 antoine100 ***@***.***>
ha scritto:

**Comment by antoine100** [comment]
10.2.0-1.1.2a is Heikili that is still suggesting Tiger palm, which is not fixed yet.
Seems to be actually working properly now this morning without any updates?

**Comment by Zifrost** [comment]
Ok, thanks for the update. I understood that for u was a good thing TP...
sorry for the misunderstandig

Il giorno gio 11 gen 2024 alle 14:08 antoine100 ***@***.***>
ha scritto:

**Comment by Hekili** [comment]
> This is not a my review of log, Just picked one random but they clearly
> suggest to not use Tiger Palm in Serenity.

They haven't written the sim profile that way.

> You have to use it before then go in Serenity.

The addon can't recommend going back in time to use Tiger Palm before you used Serenity.  So if you use Serenity and you'll need Tiger Palm (for Teachings of the Monastery or other reasons), it's going to recommend Tiger Palm.

Please be sure to add an updated snapshot of Tiger Palm being recommended so I can see/explain why it's appearing.

**Comment by Zifrost** [comment]
The snapshot I sent was good. I used TP before then used xuen and Serenity.
It was still telling me to TP>1spell I dont remember>TP.
U can see how should be the opener in raidbot link. As it is Made by apl Im
not understanding why u say "they havent written the sim profile that way".

Il giorno gio 11 gen 2024 alle 14:35 Hekili ***@***.***> ha
scritto:

**Comment by Hekili** [comment]
I need a snapshot from the current version of the addon.  When I've made updates, what's happening behind the scenes is different.  I genuinely don't understand why people think I am asking for things I don't need when I'm trying to investigate and help, but if you'd provide an updated snapshot, it'd save both of us time.  Thanks.

**Comment by Zifrost** [comment]
Ok, I will do that as soon as I go home. No problem.
We dont know how things work by ur side so u can specify that u need a need
one cuz the addon version is changed and maybe something broke.
But Ill start to thank u for all ur work!

Il giorno gio 11 gen 2024 alle 15:48 Hekili ***@***.***> ha
scritto:
