### ISSUE TITLE
[REC] ⚠️ Shadow Priest - Triple Mindbender

### ISSUE THREAD

**Issue by Thornic** [Hekili/hekili#5107]
### Before You Begin

- [x] I confirm I am using the latest version of the addon (outdated versions may have problems that were fixed on the newest release).
- [x] I confirm I am playing on official Blizzard servers (not private servers).
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I have updated the issue title to clearly describe the problem.
- [x] I am reporting an issue with the default specialization priority (not a custom or imported priority).

### Specialization

Priest - Shadow

### Describe the Issue

I had this problem when 11.2 just released, then it disappeared again. I had this problem in [v11.2.0-1.0.0h] again, but the [v11.2.0-1.0.0j] seems te have it fixed (for now).

Maybe it's fixed for good now, but I think it was a good idea to mention it here anyway.

### How to Reproduce

1. Use the M+ Balance AoE build from IcyVeins (CIQAAAAAAAAAAAAAAAAAAAAAAMMMAAAAAAAAAAAAYMWGjZmZbZjZmZmZmZZwsxMzMjZjBGjhZxsN1MDWwMAzsZZY2MAkxYBA2mB)
2. Do normal rotation, after the first Mindbender it keeps suggesting Mindbender.

### What is your information source?

Based on my own Raidbots Quick Sim results

### Snapshot (Link)

https://pastebin.com/Ab1xcKxw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fBkqTaeMTPmQT6VaLEFc6A

### Contact Information

DiscordID: Tornic.

**Comment by ctroller** [comment]
Update your addon.

Although the fix should've been in 1.0.0g, so let's keep an eye on it still.

**Comment by Thornic** [comment]
As mentioned in the description, I have updated it, and it doesn't happen with the latest update.
But because it happened with 2 different versions in a short period of time I thought it would be helpfull to mention it anyway.

**Comment by ctroller** [comment]
Relevant info for quick lookup:

```
Shadowfiend Cooldown - (34433): start=17853.88, duration=60.00, remains=57.98
Mindbender Cooldown - (200174): start=17853.88, duration=60.00, remains=57.98
Voidwraith Cooldown - (451234): start=0.00, duration=0.00, remains=0.00
Addon sees: Remaining cooldowns -  shadowfiend=0.00, mindbender=0.00, fiend=0.00
Fiend Debug - Active talents: mindbender=true, voidwraith=false
Fiend Debug - Ability data: spec.abilities.mindbender.id=nil, class.abilities.mindbender.id=200174, class.abilities.mindbender.cooldown=60
```

😕 

```
Addon sees: Remaining cooldowns -  shadowfiend=0.00, mindbender=0.00, fiend=0.00
```

that's really weird.

**Comment by ctroller** [comment]
Maybe some info, what i've seen happening: 
If i start talent swapping, from Shadowfiend to mindbender, the addon already has the Mindbender icon in the suggestions, before i've finished it. Might be related, but might also not be.

If i cancel the talent switch, it doesn't reset and keeps on Mindbender in the suggestions. Only another talent swap or reload fixes it.

Snapshot: https://pastebin.com/ktebwjP1 (i know this is a disc snapshot, but maybe it has some influence on this bug. Can open a separate ticket if you deem it worthy.)
This does _not_ always happen.

<img width="859" height="804" alt="Image" src="https://github.com/user-attachments/assets/2b012e49-8e32-4b8d-b65c-a7c795318eaf" />

**Comment by Hekili** [comment]
Is this resolved in the latest versions?

**Comment by ctroller** [comment]
Wasn't resolved in j, haven't tested the bug in k yet.

**Comment by PessimiStick** [comment]
I still see this issue in 1.0.0L

**Comment by syrifgit** [comment]
That is not the newest addon version, update your addon again.

**Comment by PessimiStick** [comment]
This can still happen in 1.0.0p 

I logged in as Disc (with Mindbender), switched to Shadow (without it) to do keys, and I was being suggested Shadow Fiend as soon as it had been on CD for 1 minute.

<img width="548" height="398" alt="Image" src="https://github.com/user-attachments/assets/475c5cdc-c5fd-42b6-ad18-447ad648145e" />

**Comment by ctroller** [comment]
Hasn't happened to me anymore, switching builds multiple times in multiple scenarios. I'll keep an eye on it further, tho.

**Comment by athcoids** [comment]
I am having this issue in v11.2.0-1.0.1d

<img width="727" height="699" alt="Image" src="https://github.com/user-attachments/assets/7ce517fa-abdc-4a3f-8433-b02f42fb63fb" />

**Comment by syrifgit** [comment]
Going to close this out for now. If anyone comes across it a new ticket can be started with proper snapshots.
